### ISSUE TITLE
Write a proposal to send encrypted pings using Glean.js

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/core-addon#130]

**Comment by Dexterp37** [comment]
The related bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1675479

**Comment by marniepw** [comment]
@Dexterp37 can you add the proposal link to this ticket? Thanks!

**Comment by Dexterp37** [comment]
There you go: https://docs.google.com/document/d/1Za-3Srfy2q3VnAnHoUMeBU0J-cEOTKS6EhnRZJz8q9A/edit?ts=5fceb8a6#

(it was in the linked bug)

**Comment by Dexterp37** [comment]
The proposal is written and it's waiting for feedback. Feedback deadline is January 15th.

**Comment by Dexterp37** [comment]
The proposal was signed off on, and approved, by the data org. Closing this.
