### ISSUE TITLE
What should `rally.js` do if no core addon is installed?

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/core-addon#171]
Right now the `rally.js` library opens a new tab from the study with the Rally website. However, this might not be the desirable outcome.

Moreover, regardless of the experience we want for end users, we might want developers to be nagged the least possible and still allow them to test locally without a problem.

cc @changecourse

**Comment by changecourse** [comment]
@Dexterp37 I've looked at this a couple of times but I think I need to understand it a bit more before providing a recommendation for what should happen. 

- In what situations would this user state occur? In what ways is rally.js present or doing anything when there isn't a core addon present? 

- What is the likelihood of us getting into this state? This will affect how much of a lift we provide this use case.

**Comment by Dexterp37** [comment]
>     * In what situations would this user state occur? In what ways is rally.js present or doing anything when there isn't a core addon present?

If users install a study without going through the website/core addon without having any core addon installed first. This can happen by installing it from AMO or by getting the XPI manually.

>     * What is the likelihood of us getting into this state? This will affect how much of a lift we provide this use case.

This is really not the golden path! I'd say low likelihood.

**Comment by changecourse** [comment]
> If users install a study without going through the website/core addon without having any core addon installed first. This can happen by installing it from AMO or by getting the XPI manually. 

But we're not allowing visibility of study add-ons within AMO, right @rhelmer (or did i misunderstand a convo we had previously?) If it's only with a manual XPI, then I can handle that as a very slight edge case...

**Comment by rhelmer** [comment]
> > If users install a study without going through the website/core addon without having any core addon installed first. This can happen by installing it from AMO or by getting the XPI manually.
> 
> But we're not allowing visibility of study add-ons within AMO, right @rhelmer (or did i misunderstand a convo we had previously?) If it's only with a manual XPI, then I can handle that as a very slight edge case...

Let's check in w/ AMO folks about this, I'm not 100% sure how hidden we can be and still be on AMO. I *think* we can be hidden from search and other listings, but there's no way to stop someone from sharing a link to the extension file itself (regardless of were the add-on is hosted).

If AMO does not fit our needs for hosting then the only other option is to self-host as we do now for Ion.

**Comment by Dexterp37** [comment]
> 
> 
> > > If users install a study without going through the website/core addon without having any core addon installed first. This can happen by installing it from AMO or by getting the XPI manually.
> > 
> > 
> > But we're not allowing visibility of study add-ons within AMO, right @rhelmer (or did i misunderstand a convo we had previously?) If it's only with a manual XPI, then I can handle that as a very slight edge case...
> 
> Let's check in w/ AMO folks about this, I'm not 100% sure how hidden we can be and still be on AMO. I _think_ we can be hidden from search and other listings, but there's no way to stop someone from sharing a link to the extension file itself (regardless of were the add-on is hosted).

@rhelmer do we have a specific requirement to be perfectly hidden? Even in a perfect world, folks could still share the link to the file

**Comment by rhelmer** [comment]
> @rhelmer do we have a specific requirement to be perfectly hidden? Even in a perfect world, folks could still share the link to the file

tbh that would be my preference... if we list the add-ons normally and support users coming in through those channels, I don't see the harm to users discovering an interesting study or the core add-on and coming in that way.

I'm trying to understand the "listed" options for AMO:
https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/

For sure we could get it signed there and self-host and not have a listing at all, I'm not sure if we can let AMO host but not get listed.

This decision is tracked in https://github.com/mozilla-ion/ion-core-addon/issues/65 (we also have https://github.com/mozilla-ion/ion-core-addon/issues/242 @Dexterp37 is that more about the documentation piece?)

In any case, we're going to hit this issue with Chrome as well. My inclination is to get comfortable with the idea that we are on a store that we don't totally control, since users to funny things even if you try to hide the URL the XPI lives on, since that must be public.

**Comment by rhelmer** [comment]
For reference, the Chrome extension store supports these options:

As a developer, you can choose to make apps and extensions available for everyone or control who can install them. There are 4 ways you can publish app and extensions in the Chrome Web Store:

-   Public—Everyone can see and install the app or extension.
-   Unlisted—Only users with the app or extension link can see and install it. The app doesn’t appear in the Chrome Web Store search results. You can share the app or extension link with users outside your domain.
-   Private—Only users in your domain can see and install the app or extension. Or, you can restrict the app or extension to trusted testers that you specified in your developer dashboard.
-   Group publishing—Only available if you pay a one-time developer signup fee. Or, if at least one extension is added to your list and set to private. For instructions, read Set up group publishing.

I'm investigating whether AMO supports something similar.

One important distinction is that Firefox supports "inline" installs of extensions, that is, we can trigger an install from any origin (website, extension, etc.) so if we really want minimum visibility then self-hosting is that, Chrome does not support this but we can at least give Firefox users a better onboarding experience.

Anyway I am asking #addons folks in slack and will report back when I have more info on what AMO offers here.

**Comment by rhelmer** [comment]
> Anyway I am asking #addons folks in slack and will report back when I have more info on what AMO offers here.

Confirmed w/ @jvillalobos on slack:

"Hosting on AMO is the equivalent of Google’s Public option. The add-on will show up on searches and you can’t turn that off. The only other option is self-distribution."

**Comment by rhelmer** [comment]
The main downside to self distribution is that we need to deal with hosting the thing and configuring updates, it's not too hard but it'd be much easier if we just let AMO handle it.

So the main decision here is if we want to appear on AMO or not, seems to be a binary choice.

**Comment by Dexterp37** [comment]
@changecourse given the conversation and the decision to go with the hosting on AMO in #65 , what about this behaviour?

**Comment by changecourse** [comment]
@Dexterp37 we'll likely need to handle this (hopefully) edge case in a couple of different ways... 

- one is at the add-on description level, trying to preemptively guide folks into our happy path by having the first line drive folks to the core add-on... (@knowtheory)

- if folks choose to ignore or bypass and install a study add-on without rally already installed, I would propose that we perform some sort of check that we bake into any study add-ons that first checks for it... if someone doesn't have Rally installed, we launch a page that directs them to installing Rally (which I can design) that is similar to the Welcome page, branded as a bridge to force installation of the Rally add-on prior to proceeding. 

- From there, we could consider a future enhancement where we're able to detect study add-on installations during onboarding for Rally, so we could fast lane folks into their "expected" study quickly (drawing from some of the same functionality of #140 perhaps)

Thoughts @Dexterp37 @rhelmer ?

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 we'll likely need to handle this (hopefully) edge case in a couple of different ways...
> 
>     * one is at the add-on description level, trying to preemptively guide folks into our happy path by having the first line drive folks to the core add-on... (@knowtheory)
> 
>     * if folks choose to ignore or bypass and install a study add-on without rally already installed, I would propose that we perform some sort of check that we bake into any study add-ons that first checks for the presence of the parent add-on... if someone doesn't have Rally installed, we launch a page that directs them to installing Rally (which I can design) that is similar to the Welcome page, branded as a bridge to force installation of the Rally add-on prior to proceeding.

Perfect. We do this already, but we don't have a specific page to point to. Let me file an issue for designing this page: https://github.com/mozilla-ion/site/issues/33

>     * From there, we could consider a future enhancement where we're able to detect study add-on installations during onboarding for Rally, so we could fast lane folks into their "expected" study quickly (drawing from some of the same functionality of #140 perhaps)
> 
> 
> Thoughts @Dexterp37 @rhelmer ?

I think that's a great way to handle this, thank you @changecourse for bearing with me

**Comment by Dexterp37** [comment]
The question was answered and there's a follow-up issue, so closing this.
