### ISSUE TITLE
when a participant uninstalls Rally through the "Leave Rally" flow, direct them to a web page that says something like "sorry to see you go"

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/core-addon#206]
Related to #205

**Comment by Dexterp37** [comment]
Note that addons allow adding an [offboarding URL](https://extensionworkshop.com/documentation/develop/onboard-upboard-offboard-users/#offboarding) to be shown when an extension is uninstalled.

**Comment by hamilton** [comment]
closing in favor of #309
