### ISSUE TITLE
study add-ons are hidden from UI on options page reload

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/core-addon#235]
If you run the core add-on locally (`web-ext` is fine) and enroll then navigate to the available studies, they are displayed and can be joined/unjoined.

However if you reload the options page (close tab and hit icon, or just press reload in the browser) then the study add-ons are hidden. I do see them for just a moment when the page loads but then they are hidden and there are no available studies, regardless of whether I have already joined a study.

**Comment by hamilton** [comment]
Thanks for filing!
