### ISSUE TITLE
Study add-ons need AMO badge (CA-P2)

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/core-addon#246]
The prompt in CA-P2 (from [this proposal](https://docs.google.com/document/d/1eS5MdZliEC0jANVUnRnAqTWiCviItsxHTNyF_brADgw/edit?disco=AAAAIwv9QB0&usp_dm=true&ts=5fabd130)) is because we're installing from an unknown origin.

Since these are signed by AMO as standard add-ons, the official supported way to do this is to have an [AMO badge](https://blog.mozilla.org/addons/2020/10/05/new-add-on-badges/) (probably "By Mozilla" or "Verified").

We need to coordinate with add-ons folks on this one.

**Comment by rhelmer** [comment]
Spoke to @jvillalobos about this, he says it should be no problem they just need to transfer ownership of the Ion Basic Study to Mozilla, and then set the appropriate recommendation.

He deferred to @wagnerand to make this change, @Dexterp37 would you mind following up on this in your morning? There is a [slack thread](https://mozilla.slack.com/archives/C4C0HCX6F/p1607548398208900) (which is ephemeral sadly) but hopefully that's enough info for him to sign off.

**Comment by Dexterp37** [comment]
Wait a second: does that mean that every study will now need to go through a special review and not through the normal AMO review process? @rhelmer ?

**Comment by rhelmer** [comment]
> Wait a second: does that mean that every study will now need to go through a special review and not through the normal AMO review process? @rhelmer ?

That's a good question, let's follow up with them. I recall from previous conversations that they wanted some kind of review process for partner add-ons in any case but we need to spell out what this means.

**Comment by Dexterp37** [comment]
> 
> 
> > Wait a second: does that mean that every study will now need to go through a special review and not through the normal AMO review process? @rhelmer ?
> 
> That's a good question, let's follow up with them. I recall from previous conversations that they wanted some kind of review process for partner add-ons in any case but we need to spell out what this means.

Indeed. We were planning on talking about that after showing them the onboarding flow.

**Comment by rhelmer** [comment]
> > > Wait a second: does that mean that every study will now need to go through a special review and not through the normal AMO review process? @rhelmer ?
> > 
> > 
> > That's a good question, let's follow up with them. I recall from previous conversations that they wanted some kind of review process for partner add-ons in any case but we need to spell out what this means.
> 
> Indeed. We were planning on talking about that after showing them the onboarding flow.

Ah yeah and we need this to show them a realistic enrollment flow, yeesh. So many chicken+egg problems laying around.

Well one nice thing is that (from what I understand from AMO folks on slack) is moving add-ons on AMO around between privileged, ownership, badged etc. is relatively easy, so we should be able to make adjustments.

For today though if we can get this going it would be really great! Let's do an ion-basic-study release so we can see if it works as expected.

**Comment by rhelmer** [comment]
I think this issue is closed for now but we still need to talk to AMO folks about what the review process and ownership of studies looks like.

**Comment by rhelmer** [comment]
> I think this issue is closed for now but we still need to talk to AMO folks about what the review process and ownership of studies looks like.

Filed https://github.com/mozilla-ion/internal/issues/21 to track this and https://github.com/mozilla-ion/ion-basic-study/issues/24 to release a new version of the study add-on.

**Comment by rhelmer** [comment]
OK we've published at least an initial version of this, which is now owned by Mozilla (instead of me which is great :)) and is badged "By Mozilla" so this prompt is suppressed.
