### ISSUE TITLE
should the integration test pull from AMO?

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/core-addon#253]
There is a certain value to testing that it works for real from AMO installs, but it is just another thing we need to keep track of, and adds latency another point of failure (network, site down, etc). Additionally, builds are not triggered when the study add-on changes.

@Dexterp37 and I discussed this in PR #228, the only two options we thought of at the time where to either:

1. build the study add-on repo
2. land a signed study add-on in the ion-core-addon repo

The problem with (1) is that it will be unsigned, so we will not be able to test that the prompt behavior is correct. (2) requires us to have a process for taking the signed study add-on from AMO and landing it in the repo, and is similar to what we do in Firefox to test this sort of behavior.

We decided not to tackle this yet, but it's something we should start thinking about.

**Comment by Dexterp37** [comment]
I think we have another option here: we could generate the study addon just for tests, as part of the test preparation. We do this quite often in m-c to test features. I quickly experimented with the approach [here](https://github.com/mozilla-ion/ion-core-addon/compare/master...Dexterp37:local_study_test).

There's a few benefits:

- it would allow us to do a full end-to-end test (rally.js to core addon) always using the most recent version of the code, meaning that any wrong change would break the tests;
- we could use this approach just for some tests, having a special test to exclusively test the prompt-less experience with the signed addon (that would be fetched from AMO);

@rhelmer , thoughts?

**Comment by marniepw** [comment]
Want to **not** pull from AMO for test, want to build the study template as part of the test.
