### ISSUE TITLE
Restrict to `en_US`

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/core-addon#263]
The legacy Pioneer experience is available to `en_US` users only. We should do the same in the core add-on.

**Comment by Dexterp37** [comment]
@rhelmer @knowtheory this is still the case, right?

**Comment by Dexterp37** [comment]
@changecourse how do you think we should handle this? How should this play out with our onboarding flow?

**Comment by changecourse** [comment]
So... just to confirm a few things: 

- can someone outside of en-us see this on AMO?

- does coverage need to be before or after add-on installation? 

If after, I assume we just need a replacement, static 'welcome' page?

**Comment by Dexterp37** [comment]
This is how the current experience looks like (legacy Ion, `about:ion` as seen from folks with a different locale):

![image](https://user-images.githubusercontent.com/883721/102375051-53f98980-3fc2-11eb-869d-b6b22a170437.png)

>     * can someone outside of en-us see this on AMO?

I believe so, yes. We should also assume they'll have access to the add-on file, so, in general, for the file to be available even if we don't want to.

>     * does coverage need to be before or after add-on installation?
>
> If after, I assume we just need a replacement, static 'welcome' page?

Yes, I think that needs to happen post installation. Yes, I believe a static `welcome` could be enough. But what do we do next? Do we just keep the thing installed?

**Comment by rhelmer** [comment]
@changecourse I've consulted w/ add-ons folks and there unfortunately is not a reliable way to do this part: 
<img width="190" alt="Screen Shot 2021-01-11 at 12 33 58 PM" src="https://user-images.githubusercontent.com/61412/104235151-66bc7e00-5409-11eb-94f4-ee4e051279ae.png">

The toolbar position is not predictable and WebExtensions cannot determine the current state. wdyt?
 
I think this is ready to implement otherwise.

**Comment by changecourse** [comment]
@rhelmer let's punt on that and just address the locale stuff for this issue. Perhaps we can open up the shortcut handling in a separate issue to discuss everything there (actually it may be in #232 already)

**Comment by rhelmer** [comment]
> @rhelmer let's punt on that and just address the locale stuff for this issue. Perhaps we can open up the shortcut handling in a separate issue to discuss everything there (actually it may be in #232 already)

Yes looks like it does, let's tackle it over there. I'd be happy to be mistaken about this ;)

**Comment by Dexterp37** [comment]
The ui will be implemented in #297
