### ISSUE TITLE
Rename `mozilla-extensions/ion-core-addon/` to `mozilla-extensions/rally-core-addon`

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/core-addon#265]
This should also:

* Update the references in the release docs;
* Make sure TC still works.

**Comment by marniepw** [comment]
@Dexterp37 can you give a quick update on this? Sounds like it's done?

**Comment by Dexterp37** [comment]
The rename happened. The fallout is being tracked in mozilla-rally/internal#18
