### ISSUE TITLE
Do we need to package all the fonts in `public/fonts`?

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/core-addon#275]
When building the core addon XPI we currently package quite a few files in the `public/font` directory (20 fonts, ~1.59MB), accounting for ~91% of the add-on size. Do we need them all?

@hamilton ?

**Comment by hamilton** [comment]
Great catch. We do not need them all. It will be straightforward to select just the individual styles we need and copy only those via the rollup config.
