### ISSUE TITLE
point Core Add-On accepted site link to staging site for now

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/core-addon#281]
Because we want to have an end-to-end QA, we should point the core add-on to the staging site. This should be straightforward; just change [this line](https://github.com/mozilla-rally/core-addon/blob/master/rollup.config.addon.js#L23) to be the staging url.

**Comment by rhelmer** [comment]
Well the patch for this is simple of course :) However I am testing against the staging site using the example in https://github.com/mozilla-rally/site/blob/86f34775da2ea95076186e5d50450e97226f1e94/src/assets/scripts/modules/rally-detection.js#L24-L27 and I haven't seen it work yet, I'm going to verify this before opening a PR.

**Comment by Dexterp37** [comment]
There's a few more occurrences of the URL in the codebase (for example [this one](https://github.com/mozilla-rally/core-addon/blob/3eac4b2c8f6e33f58084d4b9c231026c82aa373c/manifest.json#L47)). Nothing works unless we change them all. Unfortunately, unless we add a preprocessor for non JS files, we can't change it in a single place and have it effect all the code LOCs. Given that we don't expect this to be changed very frequently, maybe it's ok to grep for it for now?

**Comment by rhelmer** [comment]
Closed by https://github.com/mozilla-rally/core-addon/pull/282
