### ISSUE TITLE
Should the how it works link open in a new tab?

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/core-addon#289]
When onboarding, user can click on the "How it works" link. Doing this will open the web page inside the current tab, taking user out of the onboarding. Is this intentional, @hamilton @changecourse ?

![image](https://user-images.githubusercontent.com/883721/104005781-ecd88a80-51a5-11eb-9f33-0cd32ff12e61.png)

**Comment by hamilton** [comment]
I had this question queued up as well, thanks for asking here. I'll let @changecourse chime in. A patch would take a few minutes to get in. Addtionally, having an answer for the FAQ link would be useful.

**Comment by hamilton** [comment]
Chatted with @changecourse – this should have a blank target, as should the FAQ. I'll submit a quick PR for this.
