### ISSUE TITLE
what control do we have over this moz-extension add-on url?

### ISSUE THREAD

**Issue by changecourse** [mozilla-rally/core-addon#99]
<img width="821" alt="Screen Shot 2020-10-20 at 9 40 22 AM" src="https://user-images.githubusercontent.com/6164801/96609951-54beb980-12b8-11eb-9a18-86e3c6667924.png">

How clean vs. garbled does this name get to be between pages? 

cc: @javaun

**Comment by Dexterp37** [comment]
Note: while we might be able to make this different in Firefox, we'll definitely not be able to do that on other platforms :)

**Comment by rhelmer** [comment]
There should be a friendlier name a well 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/61412/97199116-e02ec380-176c-11eb-8d57-333166269a1b.png">

**Comment by rhelmer** [comment]
> Note: while we might be able to make this different in Firefox, we'll definitely not be able to do that on other platforms :)

Agreed, we can definitely do this for Firefox (register an `about:` page for instance) but not worth it IMHO. We've been moving more in the direction of not hiding that this is an extension.

**Comment by marniepw** [comment]
Per Rob: generated randomly client-side.

**Comment by hamilton** [comment]
We'll move forward with the extension URL as is.
